import { Comic, WishlistItem, Goal, Evento, Collection } from '@/types'

export const mockComics: Comic[] = [
  {
    id: '1',
    created_at: '2024-01-10T10:00:00Z',
    title: 'Batman: O Cavaleiro das Trevas',
    series: 'Batman',
    issue_number: 1,
    volume: null,
    publisher: 'DC Comics',
    year: 1986,
    condition: 'very_fine',
    purchase_price: 80,
    current_value: 250,
    owner: 'marcelo',
    cover_url: null,
    notes: 'Edição nacional antiga, capa dura',
    read: true,
    language: 'pt',
  },
  {
    id: '2',
    created_at: '2024-01-15T10:00:00Z',
    title: 'Watchmen #1',
    series: 'Watchmen',
    issue_number: 1,
    volume: null,
    publisher: 'DC Comics',
    year: 1986,
    condition: 'near_mint',
    purchase_price: 120,
    current_value: 400,
    owner: 'marcelo',
    cover_url: null,
    notes: null,
    read: true,
    language: 'en',
  },
  {
    id: '3',
    created_at: '2024-02-01T10:00:00Z',
    title: 'Amazing Spider-Man #300',
    series: 'Amazing Spider-Man',
    issue_number: 300,
    volume: null,
    publisher: 'Marvel Comics',
    year: 1988,
    condition: 'fine',
    purchase_price: 200,
    current_value: 600,
    owner: 'walter',
    cover_url: null,
    notes: 'Primeira aparição do Venom',
    read: true,
    language: 'en',
  },
  {
    id: '4',
    created_at: '2024-02-10T10:00:00Z',
    title: 'X-Men #1',
    series: 'X-Men',
    issue_number: 1,
    volume: null,
    publisher: 'Marvel Comics',
    year: 1991,
    condition: 'near_mint',
    purchase_price: 50,
    current_value: 80,
    owner: 'walter',
    cover_url: null,
    notes: null,
    read: false,
    language: 'en',
  },
  {
    id: '5',
    created_at: '2024-03-01T10:00:00Z',
    title: 'Sandman Vol. 1: Preludes & Nocturnes',
    series: 'Sandman',
    issue_number: null,
    volume: 1,
    publisher: 'DC/Vertigo',
    year: 1991,
    condition: 'very_fine',
    purchase_price: 90,
    current_value: 150,
    owner: 'ambos',
    cover_url: null,
    notes: 'TPB compartilhada',
    read: true,
    language: 'en',
  },
  {
    id: '6',
    created_at: '2024-03-15T10:00:00Z',
    title: 'Turma da Mônica Jovem #1',
    series: 'Turma da Mônica Jovem',
    issue_number: 1,
    volume: null,
    publisher: 'Panini',
    year: 2008,
    condition: 'mint',
    purchase_price: 15,
    current_value: 120,
    owner: 'marcelo',
    cover_url: null,
    notes: null,
    read: true,
    language: 'pt',
  },
  {
    id: '7',
    created_at: '2024-04-01T10:00:00Z',
    title: 'Watchmen #2',
    series: 'Watchmen',
    issue_number: 2,
    volume: null,
    publisher: 'DC Comics',
    year: 1986,
    condition: 'near_mint',
    purchase_price: 80,
    current_value: 200,
    owner: 'marcelo',
    cover_url: null,
    notes: null,
    read: true,
    language: 'en',
  },
  {
    id: '8',
    created_at: '2024-04-15T10:00:00Z',
    title: 'Watchmen #3',
    series: 'Watchmen',
    issue_number: 3,
    volume: null,
    publisher: 'DC Comics',
    year: 1987,
    condition: 'very_fine',
    purchase_price: 70,
    current_value: 160,
    owner: 'marcelo',
    cover_url: null,
    notes: null,
    read: true,
    language: 'en',
  },
]

export const mockWishlist: WishlistItem[] = [
  {
    id: 'w1',
    created_at: '2024-05-01T10:00:00Z',
    title: 'Watchmen #4',
    series: 'Watchmen',
    issue_number: 4,
    volume: null,
    publisher: 'DC Comics',
    priority: 'alta',
    notes: 'Para completar a série',
    owner: 'marcelo',
    estimated_price: 100,
  },
  {
    id: 'w2',
    created_at: '2024-05-05T10:00:00Z',
    title: 'Saga #1',
    series: 'Saga',
    issue_number: 1,
    volume: null,
    publisher: 'Image Comics',
    priority: 'alta',
    notes: null,
    owner: 'walter',
    estimated_price: 80,
  },
  {
    id: 'w3',
    created_at: '2024-05-10T10:00:00Z',
    title: 'Monstro do Pântano Vol. 1',
    series: 'Swamp Thing',
    issue_number: null,
    volume: 1,
    publisher: 'DC/Vertigo',
    priority: 'media',
    notes: 'Alan Moore run',
    owner: 'ambos',
    estimated_price: 120,
  },
  {
    id: 'w4',
    created_at: '2024-05-15T10:00:00Z',
    title: 'Daredevil: Born Again',
    series: 'Daredevil',
    issue_number: null,
    volume: null,
    publisher: 'Marvel Comics',
    priority: 'baixa',
    notes: null,
    owner: 'walter',
    estimated_price: 60,
  },
]

export const mockGoals: Goal[] = [
  {
    id: 'g1',
    created_at: '2024-01-01T10:00:00Z',
    title: 'Completar a série Watchmen',
    description: 'Colecionar todos os 12 números da série original',
    target_date: '2024-12-31',
    completed: false,
    owner: 'marcelo',
    type: 'serie',
    progress_current: 3,
    progress_target: 12,
  },
  {
    id: 'g2',
    created_at: '2024-01-01T10:00:00Z',
    title: 'Atingir 50 quadrinhos na coleção',
    description: null,
    target_date: '2025-06-30',
    completed: false,
    owner: 'ambos',
    type: 'quantidade',
    progress_current: 8,
    progress_target: 50,
  },
  {
    id: 'g3',
    created_at: '2024-01-01T10:00:00Z',
    title: 'Coleção vale R$ 5.000',
    description: 'Valor estimado total da coleção juntos',
    target_date: null,
    completed: false,
    owner: 'ambos',
    type: 'valor',
    progress_current: 1960,
    progress_target: 5000,
  },
]

export const mockCollections: Collection[] = [
  {
    id: 'col1',
    created_at: '2024-01-01T00:00:00Z',
    name: 'Watchmen',
    publisher: 'DC Comics',
    cover_url: null,
    total_volumes: 12,
    created_by: 'marcelo',
    description: 'Série original de 12 edições de Alan Moore e Dave Gibbons (1986–1987)',
  },
  {
    id: 'col2',
    created_at: '2024-01-01T00:00:00Z',
    name: 'Batman',
    publisher: 'DC Comics',
    cover_url: null,
    total_volumes: 3,
    created_by: 'marcelo',
    description: 'Batman: O Cavaleiro das Trevas — Frank Miller',
  },
  {
    id: 'col3',
    created_at: '2024-01-05T00:00:00Z',
    name: 'Sandman',
    publisher: 'DC/Vertigo',
    cover_url: null,
    total_volumes: 10,
    created_by: 'ambos',
    description: 'Coletânea em volumes encadernados — Neil Gaiman',
  },
  {
    id: 'col4',
    created_at: '2024-02-01T00:00:00Z',
    name: 'Amazing Spider-Man',
    publisher: 'Marvel Comics',
    cover_url: null,
    total_volumes: 441,
    created_by: 'walter',
    description: 'Edições originais da série clássica',
  },
  {
    id: 'col5',
    created_at: '2024-02-10T00:00:00Z',
    name: 'X-Men',
    publisher: 'Marvel Comics',
    cover_url: null,
    total_volumes: 279,
    created_by: 'walter',
    description: 'Série clássica dos X-Men',
  },
  {
    id: 'col6',
    created_at: '2024-03-15T00:00:00Z',
    name: 'Turma da Mônica Jovem',
    publisher: 'Panini',
    cover_url: null,
    total_volumes: 83,
    created_by: 'marcelo',
    description: 'Manga brasileiro da turma da Mônica em estilo mangá',
  },
]

export const mockEventos: Evento[] = [
  { id: 'ev1', titulo: 'Watchmen #4 — Pré-venda', data: '2026-06-25', tipo: 'pre_venda', descricao: 'Completando a série' },
  { id: 'ev2', titulo: 'Flash Sale FV Comics', data: '2026-06-28', tipo: 'saldao', descricao: '40% off em clássicos selecionados' },
  { id: 'ev3', titulo: 'Sandman Vol. 4 (Panini)', data: '2026-07-05', tipo: 'lancamento', descricao: 'Edição nacional — A Estação das Névoas' },
  { id: 'ev4', titulo: 'Saga #70 (Image Comics)', data: '2026-07-12', tipo: 'pre_venda', descricao: null },
  { id: 'ev5', titulo: 'Saldão Anime Friends SP', data: '2026-07-20', tipo: 'saldao', descricao: 'São Paulo · Estande de quadrinhos' },
  { id: 'ev6', titulo: 'X-Men #1 Facsimile (Marvel)', data: '2026-08-01', tipo: 'lancamento', descricao: null },
  { id: 'ev7', titulo: 'CCXP Mini — Pipoca & Nanquim', data: '2026-08-10', tipo: 'saldao', descricao: 'São Paulo · ago/26' },
]
